# Generated by Django 5.2.8 on 2025-11-26 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0020_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Publicação'),
        ),
        migrations.AddField(
            model_name='livros',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Produto'),
        ),
        migrations.AddField(
            model_name='livros',
            name='edicao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Edição'),
        ),
        migrations.AddField(
            model_name='livros',
            name='editora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='idioma',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='isbn10',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ISBN-10'),
        ),
        migrations.AddField(
            model_name='livros',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN-13'),
        ),
        migrations.AddField(
            model_name='livros',
            name='paginas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Páginas'),
        ),
        migrations.AddField(
            model_name='livros',
            name='sobre_autor',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre o Autor'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 15, 42, 42, 202030)),
        ),
    ]
