# Generated by Django 5.2.8 on 2025-11-26 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0021_livros_data_publicacao_livros_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 15, 45, 11, 499373)),
        ),
    ]
