# Generated by Django 5.2.8 on 2025-11-27 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0024_livros_img_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='capa_livro',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 22, 36, 18, 508538)),
        ),
    ]
