# Generated by Django 5.2.8 on 2025-11-27 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0041_alter_emprestimos_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Arquivo PDF do Livro'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 27, 6, 22, 17, 383761)),
        ),
    ]
