# Generated by Django 5.2.8 on 2025-11-29 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0046_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 12, 38, 29, 746466)),
        ),
    ]
