# Generated by Django 5.2.8 on 2025-11-30 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0051_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='data_prazo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='devolucao_planejada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 36, 16, 447084)),
        ),
    ]
