# Generated by Django 5.2.8 on 2025-11-30 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0052_emprestimos_data_prazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 57, 40, 654230)),
        ),
    ]
