# Generated by Django 5.2.8 on 2025-12-03 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0056_alter_categoria_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 3, 8, 31, 46, 922591)),
        ),
    ]
